apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xmxl4y1az-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xmxl4y1az-go 
  name: xmxl4y1az-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: xmxl4y1az-go 
